import {
  Network,
  Route,
  Sparkles,
  Quote,
  UserRound,
  Layers,
  BookOpenText,
  Eye,
  BriefcaseBusiness,
  Globe2,
  Brain,
  Link2,
  PenLine,
  LibraryBig,
  Music2,
  Drama,
  Wrench,
  TriangleAlert,
  type LucideIcon,
} from "lucide-react";
import type { CraftCategory } from "@/types/craft";

export const categoryIcons: Record<CraftCategory, LucideIcon> = {
  "Structure": Network,
  "Plot Mechanics": Route,
  "Devices": Sparkles,
  "Rhetoric & Figures": Quote,
  "Character": UserRound,
  "Theme & Symbol": Layers,
  "Narrative Delivery": BookOpenText,
  "Narratology": Eye,
  "Worldbuilding": Globe2,
  "Reader Psychology": Brain,
  "Continuity": Link2,
  "Prose & Style": PenLine,
  "Genre & Form": LibraryBig,
  "Poetry": Music2,
  "Drama": Drama,
  "Mechanical": Wrench,
  "Publishing": BriefcaseBusiness,
  "Failure Modes": TriangleAlert,
};

export type CategoryStyle = {
  iconBg: string;
  iconText: string;
  surface: string;
  accent: string;
  tileBg: string;
  tileBgHover: string;
  tileBgActive: string;
  tileChip: string;
  tileBorder: string;
  tileRing: string;
};

export const CATEGORY_ORDER: CraftCategory[] = [
  "Structure",
  "Plot Mechanics",
  "Devices",
  "Rhetoric & Figures",
  "Character",
  "Theme & Symbol",
  "Narrative Delivery",
  "Narratology",
  "Worldbuilding",
  "Reader Psychology",
  "Continuity",
  "Prose & Style",
  "Genre & Form",
  "Poetry",
  "Drama",
  "Mechanical",
  "Publishing",
  "Failure Modes",
];

// Soft, low-saturation palette — meant to differentiate categories without
// breaking the editorial monochrome feel. Hues chosen by association:
// structure→slate, motion→amber, devices→violet, character→rose,
// rhetoric→fuchsia, theme→indigo, voice→teal, narratology→blue,
// world→emerald, mind→sky, link→cyan, prose→stone, genre→yellow,
// poetry→pink, drama→red, mechanical→zinc, publishing→lime,
// failure→muted orange (not red).
export const categoryStyles: Record<CraftCategory, CategoryStyle> = {
  "Structure": {
    iconBg: "bg-slate-50",
    iconText: "text-slate-700",
    surface: "bg-slate-50/60",
    accent: "border-l-slate-300",
    tileBg: "bg-slate-50",
    tileBgHover: "hover:bg-slate-100",
    tileBgActive: "bg-slate-100",
    tileChip: "bg-slate-200",
    tileBorder: "border-slate-200",
    tileRing: "ring-slate-400",
  },
  "Plot Mechanics": {
    iconBg: "bg-amber-50",
    iconText: "text-amber-700",
    surface: "bg-amber-50/60",
    accent: "border-l-amber-300",
    tileBg: "bg-amber-50",
    tileBgHover: "hover:bg-amber-100",
    tileBgActive: "bg-amber-100",
    tileChip: "bg-amber-200",
    tileBorder: "border-amber-200",
    tileRing: "ring-amber-400",
  },
  "Devices": {
    iconBg: "bg-violet-50",
    iconText: "text-violet-700",
    surface: "bg-violet-50/60",
    accent: "border-l-violet-300",
    tileBg: "bg-violet-50",
    tileBgHover: "hover:bg-violet-100",
    tileBgActive: "bg-violet-100",
    tileChip: "bg-violet-200",
    tileBorder: "border-violet-200",
    tileRing: "ring-violet-400",
  },
  "Rhetoric & Figures": {
    iconBg: "bg-fuchsia-50",
    iconText: "text-fuchsia-700",
    surface: "bg-fuchsia-50/60",
    accent: "border-l-fuchsia-300",
    tileBg: "bg-fuchsia-50",
    tileBgHover: "hover:bg-fuchsia-100",
    tileBgActive: "bg-fuchsia-100",
    tileChip: "bg-fuchsia-200",
    tileBorder: "border-fuchsia-200",
    tileRing: "ring-fuchsia-400",
  },
  "Character": {
    iconBg: "bg-rose-50",
    iconText: "text-rose-700",
    surface: "bg-rose-50/60",
    accent: "border-l-rose-300",
    tileBg: "bg-rose-50",
    tileBgHover: "hover:bg-rose-100",
    tileBgActive: "bg-rose-100",
    tileChip: "bg-rose-200",
    tileBorder: "border-rose-200",
    tileRing: "ring-rose-400",
  },
  "Theme & Symbol": {
    iconBg: "bg-indigo-50",
    iconText: "text-indigo-700",
    surface: "bg-indigo-50/60",
    accent: "border-l-indigo-300",
    tileBg: "bg-indigo-50",
    tileBgHover: "hover:bg-indigo-100",
    tileBgActive: "bg-indigo-100",
    tileChip: "bg-indigo-200",
    tileBorder: "border-indigo-200",
    tileRing: "ring-indigo-400",
  },
  "Narrative Delivery": {
    iconBg: "bg-teal-50",
    iconText: "text-teal-700",
    surface: "bg-teal-50/60",
    accent: "border-l-teal-300",
    tileBg: "bg-teal-50",
    tileBgHover: "hover:bg-teal-100",
    tileBgActive: "bg-teal-100",
    tileChip: "bg-teal-200",
    tileBorder: "border-teal-200",
    tileRing: "ring-teal-400",
  },
  "Narratology": {
    iconBg: "bg-blue-50",
    iconText: "text-blue-700",
    surface: "bg-blue-50/60",
    accent: "border-l-blue-300",
    tileBg: "bg-blue-50",
    tileBgHover: "hover:bg-blue-100",
    tileBgActive: "bg-blue-100",
    tileChip: "bg-blue-200",
    tileBorder: "border-blue-200",
    tileRing: "ring-blue-400",
  },
  "Worldbuilding": {
    iconBg: "bg-emerald-50",
    iconText: "text-emerald-700",
    surface: "bg-emerald-50/60",
    accent: "border-l-emerald-300",
    tileBg: "bg-emerald-50",
    tileBgHover: "hover:bg-emerald-100",
    tileBgActive: "bg-emerald-100",
    tileChip: "bg-emerald-200",
    tileBorder: "border-emerald-200",
    tileRing: "ring-emerald-400",
  },
  "Reader Psychology": {
    iconBg: "bg-sky-50",
    iconText: "text-sky-700",
    surface: "bg-sky-50/60",
    accent: "border-l-sky-300",
    tileBg: "bg-sky-50",
    tileBgHover: "hover:bg-sky-100",
    tileBgActive: "bg-sky-100",
    tileChip: "bg-sky-200",
    tileBorder: "border-sky-200",
    tileRing: "ring-sky-400",
  },
  "Continuity": {
    iconBg: "bg-cyan-50",
    iconText: "text-cyan-700",
    surface: "bg-cyan-50/60",
    accent: "border-l-cyan-300",
    tileBg: "bg-cyan-50",
    tileBgHover: "hover:bg-cyan-100",
    tileBgActive: "bg-cyan-100",
    tileChip: "bg-cyan-200",
    tileBorder: "border-cyan-200",
    tileRing: "ring-cyan-400",
  },
  "Prose & Style": {
    iconBg: "bg-stone-100",
    iconText: "text-stone-700",
    surface: "bg-stone-50",
    accent: "border-l-stone-300",
    tileBg: "bg-stone-50",
    tileBgHover: "hover:bg-stone-100",
    tileBgActive: "bg-stone-100",
    tileChip: "bg-stone-200",
    tileBorder: "border-stone-200",
    tileRing: "ring-stone-400",
  },
  "Genre & Form": {
    iconBg: "bg-yellow-50",
    iconText: "text-yellow-700",
    surface: "bg-yellow-50/60",
    accent: "border-l-yellow-300",
    tileBg: "bg-yellow-50",
    tileBgHover: "hover:bg-yellow-100",
    tileBgActive: "bg-yellow-100",
    tileChip: "bg-yellow-200",
    tileBorder: "border-yellow-200",
    tileRing: "ring-yellow-400",
  },
  "Poetry": {
    iconBg: "bg-pink-50",
    iconText: "text-pink-700",
    surface: "bg-pink-50/60",
    accent: "border-l-pink-300",
    tileBg: "bg-pink-50",
    tileBgHover: "hover:bg-pink-100",
    tileBgActive: "bg-pink-100",
    tileChip: "bg-pink-200",
    tileBorder: "border-pink-200",
    tileRing: "ring-pink-400",
  },
  "Drama": {
    iconBg: "bg-red-50",
    iconText: "text-red-700",
    surface: "bg-red-50/60",
    accent: "border-l-red-300",
    tileBg: "bg-red-50",
    tileBgHover: "hover:bg-red-100",
    tileBgActive: "bg-red-100",
    tileChip: "bg-red-200",
    tileBorder: "border-red-200",
    tileRing: "ring-red-400",
  },
  "Mechanical": {
    iconBg: "bg-zinc-100",
    iconText: "text-zinc-700",
    surface: "bg-zinc-50",
    accent: "border-l-zinc-300",
    tileBg: "bg-zinc-50",
    tileBgHover: "hover:bg-zinc-100",
    tileBgActive: "bg-zinc-100",
    tileChip: "bg-zinc-200",
    tileBorder: "border-zinc-200",
    tileRing: "ring-zinc-400",
  },
  "Publishing": {
    iconBg: "bg-lime-50",
    iconText: "text-lime-700",
    surface: "bg-lime-50/60",
    accent: "border-l-lime-300",
    tileBg: "bg-lime-50",
    tileBgHover: "hover:bg-lime-100",
    tileBgActive: "bg-lime-100",
    tileChip: "bg-lime-200",
    tileBorder: "border-lime-200",
    tileRing: "ring-lime-400",
  },
  "Failure Modes": {
    iconBg: "bg-orange-50",
    iconText: "text-orange-700",
    surface: "bg-orange-50/60",
    accent: "border-l-orange-300",
    tileBg: "bg-orange-50",
    tileBgHover: "hover:bg-orange-100",
    tileBgActive: "bg-orange-100",
    tileChip: "bg-orange-200",
    tileBorder: "border-orange-200",
    tileRing: "ring-orange-400",
  },
};
