import {
  Network,
  Route,
  Sparkles,
  UserRound,
  Layers,
  BookOpenText,
  Globe2,
  Brain,
  Link2,
  PenLine,
  Wrench,
  TriangleAlert,
  type LucideIcon,
} from "lucide-react";
import type { CraftCategory } from "@/types/craft";

export const categoryIcons: Record<CraftCategory, LucideIcon> = {
  "Structure": Network,
  "Plot Mechanics": Route,
  "Devices": Sparkles,
  "Character": UserRound,
  "Theme & Symbol": Layers,
  "Narrative Delivery": BookOpenText,
  "Worldbuilding": Globe2,
  "Reader Psychology": Brain,
  "Continuity": Link2,
  "Prose & Style": PenLine,
  "Mechanical": Wrench,
  "Failure Modes": TriangleAlert,
};

export type CategoryStyle = {
  iconBg: string;
  iconText: string;
  surface: string;
  accent: string;
  tileBg: string;
  tileBgHover: string;
  tileBgActive: string;
  tileChip: string;
  tileBorder: string;
  tileRing: string;
};

export const CATEGORY_ORDER: CraftCategory[] = [
  "Structure",
  "Plot Mechanics",
  "Devices",
  "Character",
  "Theme & Symbol",
  "Narrative Delivery",
  "Worldbuilding",
  "Reader Psychology",
  "Continuity",
  "Prose & Style",
  "Mechanical",
  "Failure Modes",
];

// Soft, low-saturation palette — meant to differentiate categories without
// breaking the editorial monochrome feel. Hues chosen by association:
// structure→slate, motion→amber, devices→violet, character→rose,
// theme→indigo, voice→teal, world→emerald, mind→sky, link→cyan,
// prose→stone, mechanical→zinc, failure→muted orange (not red).
export const categoryStyles: Record<CraftCategory, CategoryStyle> = {
  "Structure": {
    iconBg: "bg-slate-50",
    iconText: "text-slate-700",
    surface: "bg-slate-50/60",
    accent: "border-l-slate-300",
    tileBg: "bg-slate-50",
    tileBgHover: "hover:bg-slate-100",
    tileBgActive: "bg-slate-100",
    tileChip: "bg-slate-200",
    tileBorder: "border-slate-200",
    tileRing: "ring-slate-400",
  },
  "Plot Mechanics": {
    iconBg: "bg-amber-50",
    iconText: "text-amber-700",
    surface: "bg-amber-50/60",
    accent: "border-l-amber-300",
    tileBg: "bg-amber-50",
    tileBgHover: "hover:bg-amber-100",
    tileBgActive: "bg-amber-100",
    tileChip: "bg-amber-200",
    tileBorder: "border-amber-200",
    tileRing: "ring-amber-400",
  },
  "Devices": {
    iconBg: "bg-violet-50",
    iconText: "text-violet-700",
    surface: "bg-violet-50/60",
    accent: "border-l-violet-300",
    tileBg: "bg-violet-50",
    tileBgHover: "hover:bg-violet-100",
    tileBgActive: "bg-violet-100",
    tileChip: "bg-violet-200",
    tileBorder: "border-violet-200",
    tileRing: "ring-violet-400",
  },
  "Character": {
    iconBg: "bg-rose-50",
    iconText: "text-rose-700",
    surface: "bg-rose-50/60",
    accent: "border-l-rose-300",
    tileBg: "bg-rose-50",
    tileBgHover: "hover:bg-rose-100",
    tileBgActive: "bg-rose-100",
    tileChip: "bg-rose-200",
    tileBorder: "border-rose-200",
    tileRing: "ring-rose-400",
  },
  "Theme & Symbol": {
    iconBg: "bg-indigo-50",
    iconText: "text-indigo-700",
    surface: "bg-indigo-50/60",
    accent: "border-l-indigo-300",
    tileBg: "bg-indigo-50",
    tileBgHover: "hover:bg-indigo-100",
    tileBgActive: "bg-indigo-100",
    tileChip: "bg-indigo-200",
    tileBorder: "border-indigo-200",
    tileRing: "ring-indigo-400",
  },
  "Narrative Delivery": {
    iconBg: "bg-teal-50",
    iconText: "text-teal-700",
    surface: "bg-teal-50/60",
    accent: "border-l-teal-300",
    tileBg: "bg-teal-50",
    tileBgHover: "hover:bg-teal-100",
    tileBgActive: "bg-teal-100",
    tileChip: "bg-teal-200",
    tileBorder: "border-teal-200",
    tileRing: "ring-teal-400",
  },
  "Worldbuilding": {
    iconBg: "bg-emerald-50",
    iconText: "text-emerald-700",
    surface: "bg-emerald-50/60",
    accent: "border-l-emerald-300",
    tileBg: "bg-emerald-50",
    tileBgHover: "hover:bg-emerald-100",
    tileBgActive: "bg-emerald-100",
    tileChip: "bg-emerald-200",
    tileBorder: "border-emerald-200",
    tileRing: "ring-emerald-400",
  },
  "Reader Psychology": {
    iconBg: "bg-sky-50",
    iconText: "text-sky-700",
    surface: "bg-sky-50/60",
    accent: "border-l-sky-300",
    tileBg: "bg-sky-50",
    tileBgHover: "hover:bg-sky-100",
    tileBgActive: "bg-sky-100",
    tileChip: "bg-sky-200",
    tileBorder: "border-sky-200",
    tileRing: "ring-sky-400",
  },
  "Continuity": {
    iconBg: "bg-cyan-50",
    iconText: "text-cyan-700",
    surface: "bg-cyan-50/60",
    accent: "border-l-cyan-300",
    tileBg: "bg-cyan-50",
    tileBgHover: "hover:bg-cyan-100",
    tileBgActive: "bg-cyan-100",
    tileChip: "bg-cyan-200",
    tileBorder: "border-cyan-200",
    tileRing: "ring-cyan-400",
  },
  "Prose & Style": {
    iconBg: "bg-stone-100",
    iconText: "text-stone-700",
    surface: "bg-stone-50",
    accent: "border-l-stone-300",
    tileBg: "bg-stone-50",
    tileBgHover: "hover:bg-stone-100",
    tileBgActive: "bg-stone-100",
    tileChip: "bg-stone-200",
    tileBorder: "border-stone-200",
    tileRing: "ring-stone-400",
  },
  "Mechanical": {
    iconBg: "bg-zinc-100",
    iconText: "text-zinc-700",
    surface: "bg-zinc-50",
    accent: "border-l-zinc-300",
    tileBg: "bg-zinc-50",
    tileBgHover: "hover:bg-zinc-100",
    tileBgActive: "bg-zinc-100",
    tileChip: "bg-zinc-200",
    tileBorder: "border-zinc-200",
    tileRing: "ring-zinc-400",
  },
  "Failure Modes": {
    iconBg: "bg-orange-50",
    iconText: "text-orange-700",
    surface: "bg-orange-50/60",
    accent: "border-l-orange-300",
    tileBg: "bg-orange-50",
    tileBgHover: "hover:bg-orange-100",
    tileBgActive: "bg-orange-100",
    tileChip: "bg-orange-200",
    tileBorder: "border-orange-200",
    tileRing: "ring-orange-400",
  },
};
